# Generated by Django 2.2.16 on 2020-10-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_misionvision'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisionyVision',
            fields=[
                ('identif', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='MisionVision',
        ),
    ]
